### PR TITLE
Fixed right click crash on Saplings by adding Null guard to ItemStack

### LINKED ISSUE #18: Right clicking golden oak sapling with empty hand or bone meal causes crash on client
Title.
Happens in a custom 1.7 magic only pack I'm working on, tested and repeatable in a standalone 1.7 instance with only ALD installed

https://mclo.gs/i9aunQV  < my 1.7 magic pack crash log

https://mclo.gs/VeKynHX < Standalone crash log

Happens on both Java 8 and Java 25, when it occurs on server it does not crash the server, only the instigating client.

### PR DESCRIPTION
**Pull request by thenextelement**
Fixed #18

### CODE REVIEW

File: src/main/java/com/gildedgames/the_aether/blocks/BlockAetherSapling.java [hunk 1]
```diff
@@ -60,13 +60,15 @@ public boolean onBlockActivated(World world, int x, int y, int z, EntityPlayer p
         	int rand = (int)(1 + Math.random() * 4);
         	if (world.getBlockLightValue(x, y + 1, z) >= 9 && rand == 4) {
         		world.setBlock(x, y, z, BlocksAether.skyroot_log, 0, 0);
+                if (!player.capabilities.isCreativeMode) {
```
Comment (havokraven) [inline src/main/java/com/gildedgames/the_aether/blocks/BlockAetherSapling.java:63]: This should not exist here. In this configuration, the item will only be consumed when the growth tick is successful. The statement:
`
if (!player.capabilities.isCreativeMode) {
  --stack.stackSize;
}
`
Should exist outside of the current if statement `if (world.getBlockLightValue(x, y + 1, z) >= 9 && rand == 4)`
